name: Componly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18

      - name: Install dependencies
        id: install-dependencies
        run: |
          echo  -e "\n@componly:registry=https://npm.pkg.github.com/" >> .npmrc
          echo //npm.pkg.github.com/:_authToken=${{secrets.COMPONLY_NPM_AUTH_TOKEN}} >> .npmrc
          yarn install

      - name: Pre scan.json
        id: pre-scan
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const { writeFileSync ,mkdirSync} = require("fs");
            const axios = require("axios");

            const instance = axios.create({
              baseURL: "https://backend-production-e808.up.railway.app",
              headers: {
                "Content-Type": "application/json",
              },
            });

            async function preScan() {
              const projectLoginResponse = await instance.post("/auth/login/cli", {
                cliId: "${{secrets.COMPONLY_API_KEY}}",
                password: "${{secrets.COMPONLY_API_SECRET}}",
              });

              const token = projectLoginResponse.data.token;

              const response = await instance.get(
                '/companies/cli/design-systems/all',
                {
                  headers: {
                    Authorization: `Bearer ${token}`
                  },
                }
              );
              mkdirSync("./.componly")
              writeFileSync("./.componly/ds.json", JSON.stringify(response.data, undefined, 2))

              console.log(response.status);
            }

            preScan().catch(console.log);

      - name: scan
        id: componly-scan
        run: yarn scan --design-systems-path ./.componly/ds.json

      - name: Post scan.json
        id: post-scan
        uses: actions/github-script@v6.4.1
        with:
          script: |
            const FormData = require("form-data");
            const { createReadStream, readFileSync } = require("fs");
            const axios = require("axios");

            const instance = axios.create({
              baseURL: "https://backend-production-e808.up.railway.app",
              headers: {
                "Content-Type": "application/json",
              },
            });

            async function postScan() {
              const serializedConfig = readFileSync("./componly.config.json");
              const { codebaseID } = JSON.parse(serializedConfig);
              const projectLoginResponse = await instance.post("/auth/login/cli", {
                cliId: "${{secrets.COMPONLY_API_KEY}}",
                password: "${{secrets.COMPONLY_API_SECRET}}",
              });

              const token = projectLoginResponse.data.token;
              const formData = new FormData();
              const fileStream = createReadStream("./.componly/scan.json");
              formData.append("file", fileStream);

              const response = await instance.post(
                `/scans/upload/${codebaseID}`,
                formData,
                {
                  headers: {
                    Authorization: `Bearer ${token}`,
                    ...formData.getHeaders(),
                  },
                }
              );

              console.log(response.status);
            }

            postScan().catch(console.log);